config/routes.rb
Rails.application.routes.draw do
  resources :enrolments
  resources :students
  resources :teachers
  resources :lessons
  resources :progresses

  root 'teachers#index'

  get '/show_enrolment', to: 'enrolments#show_enrolments'
  get '/students_class/:id', to: 'students#students_class'
  get '/update_student_progress/:id', to: 'progresses#update_student_progress'
  get '/new_progress/:id', to: 'progresses#new_progress'
end

app/models/enrolment.rb
class Enrolment < ApplicationRecord
  validates :student_id, presence: true
  validates :teacher_id, presence: true

  belongs_to :student
  belongs_to :teacher
end

app/controllers/enrolments_controller.rb
class EnrolmentsController < ApplicationController
  before_action :set_enrolment, only: [:show, :edit, :update, :destroy]

  # GET /enrolments
  # GET /enrolments.json
  def index
    @enrolments = Enrolment.all
  end

  def show_enrolments
    @enrolments = Enrolment.all
  end

  # GET /enrolments/1
  # GET /enrolments/1.json
  def show
  end

  # GET /enrolments/new
  def new
    @enrolment = Enrolment.new
  end

  # GET /enrolments/1/edit
  def edit
  end

  # POST /enrolments
  # POST /enrolments.json
  def create
    @enrolment = Enrolment.new(enrolment_params)

    respond_to do |format|
      if @enrolment.save
        format.html { redirect_to @enrolment, notice: 'Enrolment was successfully created.' }
        format.json { render :show, status: :created, location: @enrolment }
      else
        format.html { render :new }
        format.json { render json: @enrolment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrolments/1
  # PATCH/PUT /enrolments/1.json
  def update
    respond_to do |format|
      if @enrolment.update(enrolment_params)
        format.html { redirect_to @enrolment, notice: 'Enrolment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrolment }
      else
        format.html { render :edit }
        format.json { render json: @enrolment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolments/1
  # DELETE /enrolments/1.json
  def destroy
    @enrolment.destroy
    respond_to do |format|
      format.html { redirect_to enrolments_url, notice: 'Enrolment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrolment
      @enrolment = Enrolment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enrolment_params
      params.require(:enrolment).permit(:student_id, :teacher_id)
    end
end

app/helpers/enrolments_helper.rb
module EnrolmentsHelper

end

app/views/enrolments/_form.html.erb
<%= form_with(model: enrolment, local: true) do |form| %>
  <% if enrolment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(enrolment.errors.count, "error") %> prohibited this enrolment from being saved:</h2>

      <ul>
      <% enrolment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :teacher_id %>
    <%= form.text_field :teacher_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/enrolments/edit.html.erb
<h1>Editing Enrolment</h1>

<%= render 'form', enrolment: @enrolment %>

<%= link_to 'Show', @enrolment %> |
<%= link_to 'Back', enrolments_path %>

app/views/enrolments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrolments</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%  unless @enrolments.empty?  %>

        <%   @enrolments.each do |enrolment| %>
          <tr>
            <td><%= enrolment.student.name %> </td>
            <td><%= enrolment.teacher.name %></td>
            <td><%= link_to 'Show', enrolment %></td>
            <td><%= link_to 'Edit', edit_enrolment_path(enrolment) %></td>
            <td><%= link_to 'Destroy', enrolment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrolment', new_enrolment_path %>

app/views/enrolments/new.html.erb
<h1>New Enrolment</h1>

<%= render 'form', enrolment: @enrolment %>

<%= link_to 'Back', enrolments_path %>

app/views/enrolments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @enrolment.student %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @enrolment.teacher %>
</p>

<%= link_to 'Edit', edit_enrolment_path(@enrolment) %> |
<%= link_to 'Back', enrolments_path %>

app/views/enrolments/show_enrolments.html.erb
<p id="notice"><%= notice %></p>

<h1>Enrolments</h1>

<table>
  <thead>
    <tr>
      <th>Teacher</th>
      <th>Student</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrolments.each do |enrolment| %>
      <tr>
        <td><%= enrolment.teacher.fullname %></td>
        <td><%= enrolment.student.fullname %> </td>

        <td><%= link_to 'Show', enrolment %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enrolment', new_enrolment_path %>